# Generated by Django 3.2.7 on 2021-10-10 10:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=101)),
                ('slug', models.CharField(default=models.CharField(max_length=101), max_length=101)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.FloatField()),
                ('details', models.TextField()),
                ('available', models.BooleanField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 10, 10, 10, 8, 52, 689167, tzinfo=utc))),
            ],
        ),
    ]
