# Generated by Django 3.2.7 on 2021-10-10 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/iamges'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 11, 7, 31, 357331, tzinfo=utc)),
        ),
    ]
